MODEL:
  NET: 'sam' # in ['sam', 'sam-l', 'sam-adapter']
  FREEZE: True
  SAM_ONLY: True

DATASETS:
  DATA: 'coco'
  DATA_ROOT: ''  # The root of dataset
  TRAIN: 'train'    # train image path relative to dataset root
  VAL: 'valid'      # validation image path relative to dataset root
  TRAIN_ANN: '' # train annotation path relative to dataset root
  VAL_ANN: ''   # validation annotation path relative to dataset root
  PROMPT: ''     # the full path of bbox or point prompt json for validation dataset
  CROP_SIZE: (640, 640)
  RESIZE_SIZE: None
  NOISED_BBOX: False
  NOISED_RATIO: (0.64, 1.44)  # Area ratio range of noisy box relative to GT box
  PADDING: False
  MOSAIC: False

DATALOADER:
  NUM_WORKERS: 4
  IMS_PER_BATCH: 1

SOLVER:
  SAM_CKPT: ''
  WEIGHT: ''
  BASE_LR: 0.00001
  VAL_STEP: 5
  MAX_EPOCHS: 50
  MODE: 'bbox'  # in ['bbox', 'point', 'bbox_point']
  THRESHOLD: 0.8  # the threshold of pred mask
  IOU_THRESHOLD: 0.5  # the threshold of nms

EXP_NAME: 'sam'  # the experiment name, the actual output will be saved to logs/<$EXP_NAME>
